-- 코드를 작성해주세요
SELECT SUM(GR.SCORE) AS SCORE,
        EMP.EMP_NO,
        EMP.EMP_NAME,
        EMP.POSITION,
        EMP.EMAIL
FROM HR_DEPARTMENT AS DP
INNER JOIN HR_EMPLOYEES AS EMP ON DP.DEPT_ID = EMP.DEPT_ID
INNER JOIN HR_GRADE AS GR ON EMP.EMP_NO = GR.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;